# Generated by Django 2.0.6 on 2018-10-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('establishedDate', models.DateField()),
                ('operatingBudget', models.CharField(max_length=200)),
                ('numberOfEmployees', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='FormModel',
        ),
    ]
